module.exports = (client, message) => {
var x = Math.floor(Math.random() * 24)+1;  
if(message.content === "!speech"){
if(x==1){message.channel.send("Trade can bring new wealth and opportunities, but also huge disruptions and changing communities. It s a belief that pulsed in the cradle of civilization, and that still beats in the heart of billions. They know we can do better. Wright deliver a sermon called 'The Audacity of Hope.' And during the course of that sermon, he introduced me to someone named Jesus Christ. Politicians routinely exploited fears of crime for their own electoral ends. It requires all Americans to realize that your dreams do not have to come at the expense of my dreams; that investing in the health, welfare, and education of black and brown and white children will ultimately help all of America prosper. Meanwhile, the struggle for women s equality continues in many aspects of American life, and in countries around the world. On economic development, we will create a new corps of business volunteers to partner with counterparts in Muslim-majority countries. Thank you. And may God s peace be upon you.")}else
if(x==2){message.channel.send("In that time, I've had the chance to talk with Americans all across this country. And it's a lesson we need to remember today - as members of another Joshua generation. I chose to run for the presidency at this moment in history because I believe deeply that we cannot solve the challenges of our time unless we solve them together - unless we perfect our union by understanding that we may have different stories, but we hold common hopes; that we may not look the same and we may not have come from the same place, but we all want to move in the same direction - towards a better future for of children and our grandchildren. We are more compassionate than a government that lets veterans sleep on our streets and families slide into poverty; that sits on its hands while a major American city drowns before our eyes. She's the one who taught me about hard work. Words alone cannot meet the needs of our people. That we can tuck in our children at night and know that they are fed and clothed and safe from harm. If you're working forty hours a week, you shouldn't be living in poverty. And it is my first duty as President to protect the American people. But let us be clear: al Qaeda killed nearly 3,000 people on that day.Thank you.")}else
if(x==3){message.channel.send("Hall in East Moline, Ill.. And as a consequence, so did I. That's why organizations are rising up across the country to reclaim the language of faith to bring about change. Instead, they expressed a profoundly distorted view of this country - a view that sees white racism as endemic, and that elevates what is wrong with America above all that we know is right with America; a view that sees the conflicts in the Middle East as rooted primarily in the actions of stalwart allies like Israel, instead of emanating from the perverse and hateful ideologies of radical Islam. He simply says to everyone in the room, 'I am here because of Ashley.' I'll invest in early childhood education. The hope of a skinny kid with a funny name who believes that America has a place for him, too. And it's a testament to what we can achieve when good people with strong convictions stand up for their beliefs. And Ashley said that when she was nine years old, her mother got cancer. Washington's been talking about our oil addiction for the last thirty years, and John McCain has been there for twenty-six of them. More recently, tension has been fed by colonialism that denied rights and opportunities to many Muslims, and a Cold War in which Muslim-majority countries were too often treated as proxies without regard to their own aspirations. Thank you, God Bless you, and God Bless the United States of America.")}else
if(x==4){message.channel.send("That we can say what we think, write what we think, without hearing a sudden knock on the door. There is not a Black America and a White America and Latino America and Asian America - there's the United States of America. And we should close Guantanamo Bay and stop tolerating the torture of our enemies. But the record's clear: John McCain has voted with George Bush ninety percent of the time. Out of work? Tough luck. The fundamentals we use to measure economic strength are whether we are living up to that fundamental promise that has made this country great - a promise that is the only reason I am standing here tonight. The UCC is still listening. And Ashley said that when she was nine years old, her mother got cancer. Because it feeds into the cynicism we all have about government. But all of us must recognize that education and innovation will be the currency of the 21st century, and in too many Muslim communities there remains underinvestment in these areas. The question is whether we spend that time focused on what pushes us apart, or whether we commit ourselves to an effort - a sustained effort - to find common ground, to focus on the future we seek for our children, and to respect the dignity of all human beings. Thank you.")}else
if(x==5){message.channel.send("Wright deliver a sermon called 'The Audacity of Hope.' And during the course of that sermon, he introduced me to someone named Jesus Christ. If John McCain wants to follow George Bush with more tough talk and bad strategy, that is his choice - but it is not the change we need. So America will defend itself respectful of the sovereignty of nations and the rule of law. But we have a responsibility to join together on behalf of the world we seek - a world where extremists no longer threaten our people, and American troops have come home; a world where Israelis and Palestinians are each secure in a state of their own, and nuclear energy is used for peaceful purposes; a world where governments serve their citizens, and the rights of all God's children are respected. I know there are many - Muslim and non-Muslim - who question whether we can forge this new beginning. But if we choose to be bound by the past, we will never move forward.")}else
if(x==6){message.channel.send("It wasn't until after college, when I went to Chicago to work as a community organizer for a group of Christian churches, that I confronted my own spiritual dilemma. It's a promise that says each of us has the freedom to make of our own lives what we will, but that we also have the obligation to treat each other with dignity and respect. For human history has often been a record of nations and tribes subjugating one another to serve their own interests. Rather than remain trapped in the past, I have made it clear to Iran's leaders and people that my country is prepared to move forward.")}else
if(x==7){message.channel.send("We meet at one of those defining moments - a moment when our nation is at war, our economy is in turmoil, and the American promise has been threatened once more. The truth is, on issue after issue that would make a difference in your lives - on health care and education and the economy - Senator McCain has been anything but independent.")}else
if(x==8){message.channel.send("E pluribus unum. This time we want to talk about the fact that the real problem is not that someone who doesn't look like you might take your job; it's that the corporation you work for will ship it overseas for nothing more than a profit. America, we are better than these last eight years. What is that promise? Some are eager to stoke the flames of division, and to stand in the way of progress.")}else
if(x==9){message.channel.send("When we send our young men and women into harm's way, we have a solemn obligation not to fudge the numbers or shade the truth about why they're going, to care for their families while they're gone, to tend to the soldiers upon their return, and to never ever go to war without enough troops to win the war, secure the peace, and earn the respect of the world. A nation of whiners? Tell that to the proud auto workers at a Michigan plant who, after they found out it was closing, kept showing up every day and working as hard as ever, because they knew there were people who counted on the brakes that they made. I'll invest in early childhood education. But what I will not do is suggest that the Senator takes his positions for political purposes. For eighteen long months, you have stood up, one by one, and said enough to the politics of the past.")}else
if(x==10){message.channel.send("At every opportunity, they've told evangelical Christians that Democrats disrespect their values and dislike their Church, while suggesting to the rest of the country that religious Americans care only about issues like abortion and gay marriage; school prayer and intelligent design. Nor is it beyond the sea. That's why I stand here tonight. America, we cannot turn back. The United States has been one of the greatest sources of progress that the world has ever known.")}else
if(x==11){message.channel.send("I've seen it in Washington, when we worked across party lines to open up government and hold lobbyists more accountable, to give better care for our veterans and keep nuclear weapons out of terrorist hands. But let us be clear: al Qaeda killed nearly 3,000 people on that day. But it was not violence that won full and equal rights.")}else
if(x==12){message.channel.send("It's a promise that says the market should reward drive and innovation and generate growth, but that businesses should live up to their responsibilities to create American jobs, look out for American workers, and play by the rules of the road. Don't tell me that Democrats won't keep us safe.")}else
if(x==13){message.channel.send("You know, a while back, I met a young man named Shamus [Seamus?] in a V.F.W. Now, some of you may have heard me talk about the Joshua generation. We will, however, relentlessly confront violent extremists who pose a grave threat to our security. Now is the time for Palestinians to focus on what they can build. This is important because no development strategy can be based only upon what comes out of the ground, nor can it be sustained while young people are out of work.")}else
if(x==14){message.channel.send("And that it's not enough to just believe this - we have to do our part to make it a reality. In the white community, the path to a more perfect union means acknowledging that what ails the African-American community does not just exist in the minds of black people; that the legacy of discrimination - and current incidents of discrimination, while less overt than in the past - are real and must be addressed. He does not say education or the war.")}else
if(x==15){message.channel.send("They held vigils across this country when four little girls were killed in the 16th Street Baptist Church. We can affirm our faith without endangering the separation of church and state, as long as we understand that when we're in the public square, we have to speak in universal terms that everyone can understand. It is easy to point fingers - for Palestinians to point to the displacement brought by Israel's founding, and for Israelis to point to the constant hostility and attacks throughout its history from within its borders as well as beyond. God bless you.")}else
if(x==16){message.channel.send("And so they need an assurance that somebody out there cares about them, is listening to them - that they are not just destined to travel down that long road toward nothingness. And as a consequence, so did I. And when these battles were overtaken by others and when the wars they opposed were waged and won, these faithful foot soldiers for justice kept marching. So let me spell out exactly what that change would mean if I am President. Without these ingredients, elections alone do not make true democracy.")}else
if(x==17){message.channel.send("The day after Pearl Harbor my grandfather signed up for duty; joined Patton's army, marched across Europe. It's the hope of slaves sitting around a fire singing freedom songs. I would not be running for President if I didn't believe with all my heart that this is what the vast majority of Americans want for this country. It is not enough to give health care to the sick, or jobs to the jobless, or education to our children. Out of work? Tough luck. Indeed, it suggests the opposite: we must face these tensions squarely.")}else
if(x==18){message.channel.send("John Edwards calls on us to hope. At every opportunity, they've told evangelical Christians that Democrats disrespect their values and dislike their Church, while suggesting to the rest of the country that religious Americans care only about issues like abortion and gay marriage; school prayer and intelligent design. You don't protect Israel and deter Iran just by talking tough in Washington.")}else
if(x==19){message.channel.send("And it puts the lie to the notion that the separation of church and state in America means faith should have no role in public life. But if we see this conflict only from one side or the other, then we will be blind to the truth: the only resolution is for the aspirations of both sides to be met through two states, where Israelis and Palestinians each live in peace and security.")}else
if(x==20){message.channel.send("Because one of the things that we have to change in our politics is the idea that people cannot disagree without challenging each other's character and patriotism. Instead, it is that American spirit - that American promise - that pushes us forward even when the path is uncertain; that binds us together in spite of our differences; that makes us fix our eye not on what is seen, but what is unseen, that better place around the bend. Iraq's sovereignty is its own.")}else
if(x==21){message.channel.send("And I've found that no matter where I am, or who I'm talking to, there's a common theme that emerges. Many bring up a specific issue. Now is the time to finally keep the promise of affordable, accessible health care for every single American. But let us be clear: al Qaeda killed nearly 3,000 people on that day. The Arab-Israeli conflict should no longer be used to distract the people of Arab nations from other problems.")}else
if(x==22){message.channel.send("I'm talking about something more substantial. I've seen it in the workers who would rather cut their hours back a day than see their friends lose their jobs, in the soldiers who re-enlist after losing a limb, in the good neighbors who take a stranger in when a hurricane strikes and the floodwaters rise. It was Islam - at places like Al-Azhar University - that carried the light of learning through so many centuries, paving the way for Europe's Renaissance and Enlightenment. They have affiliates in many countries and are trying to expand their reach. We are taking concrete actions to change course. And we will also expand partnerships with Muslim communities to promote child and maternal health.")}else
if(x==23){message.channel.send("But it is a story that has seared into my genetic makeup the idea that this nation is more than the sum of its parts - that out of many, we are truly one. We can tackle race only as spectacle - as we did in the OJ trial - or in the wake of tragedy, as we did in the aftermath of Katrina - or as fodder for the nightly news. And it is on their behalf that I intend to win this election and keep our promise alive as President of the United States. The United States does not accept the legitimacy of continued Israeli settlements.")}else
if(x==24){message.channel.send("If there is a child on the south side of Chicago who can't read, that matters to me, even if it's not my child. They stood on the Edmund Pettus Bridge, as the blows of billy clubs rained down. Religious leaders like my friends Rev. Jim Wallis and Rabbi David Saperstein and Nathan Diament are working for justice and fighting for change. We meet at one of those defining moments - a moment when our nation is at war, our economy is in turmoil, and the American promise has been threatened once more. But the failure to respond is a direct result of a broken politics in Washington and the failed policies of George W. Bush. Countries like Japan and South Korea grew their economies while maintaining distinct cultures.")}






}
if(message.content === "!s"){
message.channel.send("jena ljeh alsgjnasglajksegn ljn gklwagn alwneg alwngaw")
}

//jena ljeh alsgjnasglajksegn ljn gklwagn alwneg alwngaw






}